FROM osixia/openldap:1.1.9

ENV COMPOSE_HTTP_TIMEOUT 200
ENV LDAP_LOG_LEVEL 256
ENV LDAP_ORGANISATION Phest
ENV LDAP_DOMAIN phets.com
ENV LDAP_ADMIN_PASSWORD admin
ENV LDAP_CONFIG_PASSWORD config
ENV LDAP_READONLY_USER false
ENV LDAP_BACKEND hdb
ENV LDAP_TLS true
ENV LDAP_TLS_CRT_FILENAME ldap.crt
ENV LDAP_TLS_KEY_FILENAME ldap.key
ENV LDAP_TLS_CA_CRT_FILENAME ca.crt
ENV LDAP_TLS_ENFORCE false
ENV LDAP_TLS_CIPHER_SUITE SECURE256:-VERS-SSL3.0
ENV LDAP_TLS_PROTOCOL_MIN 3.1
ENV LDAP_TLS_VERIFY_CLIENT demand
ENV LDAP_REPLICATION false
ENV LDAP_REMOVE_CONFIG_AFTER_SETUP true
ENV LDAP_SSL_HELPER_PREFIX ldap

